---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
        identity: grpc-client
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: grpc-client
        image: buoyantio/strest-grpc:latest
        args:
        - "client"
        - "--address=stage.grpc-server.global:80"
        - "--connections=4"
        - "--totalTargetRps=4"
        - "--totalRequests=40"
        - "--logLevel=debug"
        resources:
          requests:
            cpu: "30m"
            memory: "100Mi"
          limits:
            cpu: "60m"
            memory: "200Mi"
