apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-service1
  namespace: sample
  labels:
    identity: greeting
    env: stage
spec:
  policy:
    - dns: default
      lbType: 0
