version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/admiral
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        name: Setting BRANCH, TAG & SHA variables
        command: |
          echo "export TAG=$CIRCLE_TAG" >> $BASH_ENV
          echo "$TAG"
          echo "export BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
          echo "$BRANCH"
          echo "export SHA=$CIRCLE_SHA1" >> $BASH_ENV
          echo "$SHA"
          source $BASH_ENV
    - run:
        name: Build
        command: |
          make build
    - run:
        name: Tests
        command: |
          make test
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          make docker-build
    - run:
        name: Publish Docker image
        command: |
          make docker-publish
