apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clientconnectionconfigs.admiral.io
spec:
  group: admiral.io
  names:
    kind: ClientConnectionConfig
    listKind: ClientConnectionConfigList
    plural: clientconnectionconfigs
    shortNames:
      - ccc
    singular: clientconnectionconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                connectionPool:
                  properties:
                    http:
                      description: HTTP connection pool settings
                      properties:
                        h2UpgradePolicy:
                          format: int32
                          type: integer
                        http1MaxPendingRequests:
                          description: Maximum number of pending HTTP requests to a
                            destination.
                          format: int32
                          type: integer
                        http2MaxRequests:
                          description: Maximum number of requests to a backend
                          format: int32
                          type: integer
                        idleTimeout:
                          description: The idle timeout for upstream connection
                          type: string
                        maxRequestsPerConnection:
                          description: Maximum number of requests per connection to
                            a backend.
                          format: int32
                          type: integer
                        maxRetries:
                          format: int32
                          type: integer
                        useClientProtocol:
                          type: boolean
                      type: object
                    tcp:
                      properties:
                        connectTimeout:
                          description: TCP connection timeout.
                          type: string
                        maxConnectionDuration:
                          description: The maximum duration of a connection
                          type: string
                        maxConnections:
                          description: Maximum number of HTTP1 /TCP connections to a
                            destination host.
                          format: int32
                          type: integer
                        tcpKeepalive:
                          properties:
                            interval:
                              description: The time duration between keep-alive probes.
                              type: string
                            probes:
                              format: int32
                              type: integer
                            time:
                              type: string
                          type: object
                      type: object
                  type: object
                tunnel:
                  properties:
                    protocol:
                      type: string
                    targetHost:
                      type: string
                    targetPort:
                      format: int32
                      type: integer
                  type: object
              type: object
            status:
              properties:
                clustersSynced:
                  format: int32
                  type: integer
                state:
                  type: string
              required:
                - clustersSynced
                - state
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true