apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker.io/admiralproj/admiral
  newName: docker.io/admiralproj/admiral
  newTag: latest


patchesStrategicMerge:
- envconfig_values.yaml

resources:
- ns.yaml
- ../../base
